"""users schema

Revision ID: 442453a44c03
Revises:
Create Date: 2026-07-19 12:24:52.628034

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "442453a44c03"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
