"""holiday models

Revision ID: 993df4c0fdad
Revises: 4ac94f87c343
Create Date: 2026-07-19 21:44:01.823408

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "993df4c0fdad"
down_revision: str | Sequence[str] | None = "4ac94f87c343"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
