"""reservation schema

Revision ID: 9ff6e08c168e
Revises: 19a03ca09e7f
Create Date: 2026-07-21 22:56:04.824336

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9ff6e08c168e"
down_revision: str | Sequence[str] | None = "19a03ca09e7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
